### ISSUE TITLE
 New version pointing to latest version of specflow

### ISSUE THREAD

**Issue by winstondz** [reportportal/agent-net-specflow#54] opened 2020-07-02 04:35 UTC
I am receiving an error where its looking for the older specflow version (3.1.0) when using v3.0.0? Is there a new one which points to v3.3.30 of specflow.
Also when using nunit as the test runner, for specflow scenarios with @ignore tag, the report portal tests don't end, but are stuck with a status of 'in progress' . Will this nuget package resolve that issue? I am using the nunit report portal agent which does not handle the ignored scenarios, so was hoping to migrate to this one.

**Comment by nvborisenko** [comment] 2020-07-02 09:04
1. Cannot reproduce issue with versions mismatching. The latest beta requires SpecFlow >= 3.1.80 You can see minimum supported version on https://www.nuget.org/packages/ReportPortal.SpecFlow/3.0.0-beta.3
![image](https://user-images.githubusercontent.com/22616990/86338559-2494d180-bc5b-11ea-9ec7-0f6610429057.png)

The coming release will require v3.3.0 as minimum supported version.

2. Also I cannot reproduce issue with `@ignore` tag using `v3.0.0-beta.3`. I just don't see ignored scenario on RP. Hmm, I prefer to see it as skipped. Submitted issue #55 

Could you please prepare simple test project to highlight issues?

**Comment by nvborisenko** [comment] 2020-07-08 13:05
@winstondz closing it, feel free to reopen.

**Closed by nvborisenko** 2020-07-08 13:05 UTC

**Comment by winstondz** [comment] 2020-07-23 16:50
Sorry. I have been off for the week. I was able to resolve it by re installing the packages
