### ISSUE TITLE
Сorrect display of retry tests

### ISSUE THREAD

**Issue by AlexanderTishchenko** [reportportal/agent-net-specflow#36] opened 2019-01-15 13:45 UTC
In my project we run tests in Jenkins. I implemented possibility to rerun failed tests in Jenkins pipeline.
We start to run all tests by nunit console and then when it finished, for rerun we give the list of failed tests names to nunit console again as a separate run. For both run and rerun we use the same launch id. But finaly in report portal rerunned test looks like a separate test ![rerun_test](https://user-images.githubusercontent.com/42754200/51183766-496c7c00-18e3-11e9-8cb7-d4f9bcf2d83c.png)
As I know in API in StartTestItemRequest and FinishTestItemRequest there is a property retry
![retry_property](https://user-images.githubusercontent.com/42754200/51183905-c3046a00-18e3-11e9-81e2-c41c7392d5f7.png)
Is it possible to specify this property by ReportPortal.SpecFlow plugin? Because I want my reruned tests to be shown as in documentation 
![documentation](https://user-images.githubusercontent.com/42754200/51184043-360de080-18e4-11e9-8d50-64d04278222c.png)

**Comment by nvborisenko** [comment] 2019-01-17 12:12
Based on my experiments It seems that TestItem should be started with "retry" property in http request. The issue is even if we report next test items as retries, the first test item must be created with "retry" property. Mmm, but agent doesn't know whether test will be executed again.

Retry should be improved on API side.

@aliaksandrbasau https://github.com/reportportal/client-net/blob/master/ReportPortal.Client.Tests/TestItem/TestItemFixture.cs example with retry (test name is "RetryTest")

**Comment by DzmitryHumianiuk** [comment] 2019-01-18 07:36
it's only in @avarabyeu head for now

**Comment by aliaksandrbasau** [comment] 2019-02-02 21:08
@AlexanderTishchenko Sorry about the delayed response! @nvborisenko is right. The retry functionality is not fully usable at this point since you would have to set `retry=true` for all test items during the initial run and you would have to rerun test without closing the initial launch.
I would wait for the RERUN functionality (https://github.com/reportportal/reportportal/issues/363).
If you need retry functionality now, I see at least two options.

##### Rerun
1. Report all Scenario test items as reruns during the initial run and don't finish the launch if there are failed tests.
2. Compile the list of failed tests and run them. You would have to modify your testing solution a) not to start a new launch but use the initial one, b) instead of creating new test items for Features, find ones that were created during the initial run, c) report Scenario test items with `retry=true`.

##### Deep merge
1. Create two separate runs and finish them.
2. Remove rerun scenarios from the initial run.
3. Do a deep merge.

The downside is that you loose the previous attempts.

@AlexanderTishchenko Question about `as a separate run` and `we use the same launch id`. Are you closing RP launch before starting rerun?

**Comment by AlexanderTishchenko** [comment] 2019-02-04 08:39
@aliaksandrbasau 
> @AlexanderTishchenko Question about `as a separate run` and `we use the same launch id`. Are you closing RP launch before starting rerun?
No, I tried to report both run and rerun in a single launch, I thought that they will be merged as it mentioned in documentation.
Now I implemented "Deep merge" option and I'll wait for RERUN functionality (reportportal/reportportal#363).
Thank you for your unswer?

**Comment by DzmitryHumianiuk** [comment] 2019-04-10 17:55
related to
https://github.com/reportportal/reportportal/issues/363

**Comment by nvborisenko** [comment] 2020-05-26 10:45
Rerun is here. Please try v3.0.0-beta.2 which is compatible only with RP5+. Before rerunning your failed tests, set `Launch:Rerun` configuration property to `true`.

https://github.com/reportportal/commons-net/blob/develop/docs/Configuration.md#reporting-experience

**Closed** 2020-05-26 10:45 UTC
